#!/usr/bin/bash

# > curl https://do_dotfiles.savor.page | sh

sudo apt update && sudo apt install -y curl git

(
	echo "Clone dotfiles..."
	cd $HOME && 
	git clone https://github.com/jrmysvr/dotfiles && 
	cd dotfiles && 
	bash setup.sh
)

echo "All done"
